"use strict";
$(document).ready(function() {
    $('#toggle').click(function() {
        $(this).toggleClass('active');
        $('#overlay').toggleClass('open');
    });
    /***********a var object with 2 other objects******************/
    let translationArr = {
        'fr': {
            'home': "Accueil",
            'job': "Integratrice web",
            'pj': "Portfolio",
            'introduce': "Presentation",
            'exp': "Experiences",
            'timeline': "Parcours",
            'cv': "Presentation",
            'pj': "Portfolio",
            'sk': "Competences",
            'pg': "Langages informatiques",
            'wd': "Webdesign",
            'dv': "Divers",
            "inf": 'Infographie',
            'fs': "Veille strategique",
            't': "Parcours",
            'tn': "Foussana | Tunisie",
            'ie': "Dublin | Irlande",
            'pt': "Lisbonne | Portugal",
            'tFirst': "Mediatrice numerique | Echanges Phoceens",
            'tSecond': "Developpeur web | Formation Simplonmars",
            'tThird': "Vendeuse | Artisans du Monde",
            'tForth': "Agente d'accueil | UEFA",
            'tFifth': "Master Tourisme Langues et Patrimoine | Aix-Marseille Universite",
            'tSixth': "Assistante logistique | Benetton",
            'tSeventh': "Bibliothecaire | Aix-Marseille Universite",
            'tEighth': "Assistante de français | Ecole et Collège de Amarante",
            'tNinth': "Assistante de Direction | Schindler Ireland",
            'tTenth': "Programme Erasmus | Universidade Catolica Portuguesa ",
            'tEleventh': "Langues Etrangères Appliquees specialite affaires et commerce | Aix-Marseille Universite",
            'aa': "Sensibilisation au numerique",
            'ab': "Presentation des langages de programmation HTML/CSS",
            'ac': "Apprentissage de la conception de pages web",
            'ba': "Apprentissage des langages de programmation et des librairies",
            'bb': "Gestion de projets individuels et collectifs",
            'bc': "Utilisation du logiciel Linux",
            'ca': "Presentation de la surface de vente",
            'cb': "Accueil de la clientèle",
            'cc': "Gestion du stand de vente de la Foire de Marseille 2015 et du marche du Merlan",
            'da': "Accueil des spectateurs",
            'db': "Verification des billets",
            'dc': "Orientation des supporters",
            'ea': "Conduite de projets",
            'eb': "Economie du tourisme",
            'ec': "Histoire de l'art",
            'fa': "Contrôle qualite",
            'fb': "Gestion des commandes",
            'fc': "Gestion des litiges",
            'fd': "Suivi logistique: mode de conditionnement",
            'ga': "Accueil du public",
            'gb': "Creation et gestion d'une base de donnees",
            'gc': "Conseil des documents (livres et revues) auprès des etudiants",
            'gd': "Aide pedagogique aux etudiants: exposes, dissertation, thèses...",
            'ha': "Creation, gestion et organisation des activites ludiques et pedagogiques",
            'hb': "Travail d'equipe avec les enseignants",
            'hc': "Promotion de la langue française",
            'ia': "Envoi des factures et retards de paiement",
            'ib': "Planification des voyages d'affaires",
            'ic': "Redaction de notes de synthèses en français et en anglais",
            'ja': "Communication en entreprise",
            'jb': "Gestion des organisations",
            'jc': "Infographie - webdesign",
            'ka': "Economie",
            'kb': "Gestion et comptabilite",
            'kc': "Marketing",
            'kd': "Developpement strategique à l'international",
            'contact': "Contact",
            'legal': "Mentions legales"
        },
        'en': {
            'home': "Home",
            'cv': "Resume",
            'job': "Web integrator",
            'pj': "Works",
            'introduce': "About me",
            'exp': "Skills",
            'timeline': "Timeline",
            'contact': "Contact",
            'sk': "Skills",
            'pg': "Programmation languages",
            'wd': "Webdesign",
            'dv': "Unclassified",
            "inf": 'Infographic',
            'fs': "Strategic foresight",
            't': "Timeline",
            'tFirst': "Mediator | Echanges Phoceens",
            'tSecond': "Web developper | Simplonmars Training",
            'tThird': "Volunteer Sales | Artisans du Monde",
            'tForth': "Volunteer Spectator Services | UEFA",
            'tFifth': "Master Degree in Tourism Languages and Patrimony | Aix-Marseille Universite (AMU)",
            'tSixth': "Logistic assistant | Benetton",
            'tSeventh': "Librarian | AMU",
            'tEighth': "French assistant | Amarante school",
            'tNinth': "Executive assitant | Schindler Ireland",
            'tTenth': "Erasmus Exchange | Universidade Catolica Portuguesa ",
            'tEleventh': 'Applied Foreign Languages: Business and Trading | AMU',
            'tn': "Foussana | Tunisia",
            'ie': "Dublin | Ireland",
            'pt': "Lisbon | Portugal",
            'aa': "Promote programming jobs",
            'ab': "Introduction to the programming languages: HTML/CSS",
            'ac': "Teaching webpage design",
            'ba': "Learn programming languages and frameworks",
            'bb': "Manage individual and team projects",
            'bc': "Use of Linux",
            'ca': "Place fair trade products on the shelves",
            'cb': "Welcome clients",
            'cc': "Manage stands at international fairs and markets",
            'da': "Welcome spectators",
            'db': "Check tickets",
            'dc': "Usher spectators in the stadium",
            'ea': "Project management",
            'eb': "Tourism econonomics",
            'ec': "Art history",
            'fa': "Quality control",
            'fb': "Order management",
            'fc': "Dispute management",
            'fd': "Logistic coordination",
            'ga': "Host readers",
            'gb': "Create and manage a database",
            'gc': "Recommend books and reviews to the students",
            'gd': "Provide pedagogic method: essays, dissertations, thesis...",
            'ha': "Create, manage and organize educational activities",
            'hb': "Team work with teachers",
            'hc': "Promote French language",
            'ia': "Send invoices and overdue paiements",
            'ib': "Plan business trips",
            'ic': "Typewrite notes in French and English",
            'ja': "Corporate communication",
            'jb': "Charity Management",
            'jc': "Infographics",
            'ka': "Economics",
            'kb': "Management and accountability",
            'kc': "Marketing",
            'kd': "Developing international trade",
            'legal': "Mentions"
        },
        'pt': {
            'home': "Inicio",
            'cv': "Curriculo",
            'job': "Integradora web",
            'pj': "Portfolio",
            'sk': "Competências",
            'pg': "Linguagens de programação",
            'wd': "Webdesign",
            'exp':"Evolução profissional",
            'dv': "Outros",
            't': "Historico",
            'tFirst': "Animadora| Echanges Phoceens",
            'tSecond': "Desenvolvedor web  | Formação Simplonmars",
            'tThird': "Vendora | Artisans du Monde",
            'tForth': "Rececionista | UEFA",
            'tFifth': "Mestrado Turismo Linguas e Patrimonio | Aix-Marseille Universite (AMU)",
            'tSixth': "Assistente logistico | Benetton",
            'tSeventh': "Bibliotecário | AMU",
            'tEighth': "Assistente de francês | Amarante school",
            'tNinth': "Assistente executivo | Schindler Ireland",
            'tTenth': "Mobilidade Livre Erasmus  | Universidade Catolica Portuguesa ",
            'tEleventh': 'Linguas Estrangeiras Aplicados: Comercio e Negocios | AMU',
            'tn': "Foussana | Tunisia",
            'ie': "Dublin | Irlândia",
            'pt': "Lisboa | Portugal",
            'aa': "Promoção nos empregos da programação",
            'ab': "Presentação das linguagens de programação: HTML/CSS",
            'ac': "Ensino do webdesign",
            'ba': "Aprentissagem das linguagens de programação e dos frameworks",
            'bb': "Gestão dos projetos individuais e colectivos",
            'bc': "Uso do Linux",
            'ca': "Presentação da área de venda",
            'cb': "Acolhimento dos clientes",
            'cc': "Gestão da venda nas feiras e mercados",
            'da': "Receção dos fãs",
            'db': "Verificação dos bilhetes",
            'dc': "Orientar os espectadores no estádio",
            'ea': "Gestão dos projetos",
            'eb': "Economia do turismo",
            'ec': "Historia do arte",
            'fa': "Controlo qualidade",
            'fb': "Gestão das encomendas",
            'fc': "Gestão dos conflitos",
            'fd': "Supervisão logistica",
            'ga': "Receção do público estudantil",
            'gb': "Criação e gestão dum banco de dados",
            'gc': "Ajuda no escolho de libros e revistas na pesquisa universitário",
            'gd': "Estructurar um metodo pedagogico dos estudantes",
            'ha': "Organização das atividades lúdicas",
            'hb': "Trabalho em colaboração com os professores",
            'hc': "Promoção da lingua francesa",
            'ia': "Enviar das facturas e atraso de pagamento",
            'ib': "Organização de viagens professionais",
            'ic': "Redação relatorios em francês e inglês",
            'id': "Prospecção de empresas",
            'ja': "Comunicação organizacional",
            'jb': "Gestãoion das organizações",
            'jc': "Infografia/Webdesign",
            'ka': "Economia",
            'kb': "Gestão e contabilidade",
            'kc': "Marketing",
            'kd': "Desenvolvimento estrategico no internacional",
            'contact': "Contacto",
            "inf": 'Infografia',
            'fs': "Prospecção estrategica",
            'legal': "Menções legais"
        }
    };
    /**************loop lang elements to each item when element translate class is clicked***************/
    $(function() {
        /*****create an event onclick******************/
        $('.translate').click(function() {
            /**********create a var*************/
            var languages = $(this).attr('id');
            /**********target the class lang for the change*************/
            $('.lang').each(function(index, element) {
                $(this).text(translationArr[languages][$(this).attr('key')]);

            });
        });
    });
});
