"use strict";
$(document).ready(function() {
    $('#toggle').click(function() {
        $(this).toggleClass('active');
        $('#overlay').toggleClass('open');
    });
    /***********a var object with 2 other objects******************/
    let translationArr = {
        'fr': {
            'home': "Accueil",
            'cv': "Présentation",
            'pj': "Portfolio",
            'contact': "Contact",
            't': "Parcours",
            'tn':"Foussana | Tunisie",
            'ie':"Dublin | Irlande",
            'pt':"Lisbonne | Portugal",
            'tFirst': "Médiatrice numérique | Echanges Phocéens",
            'tSecond': "Developpeur web | Formation Simplonmars",
            'tThird': "Vendeuse | Artisans du Monde",
            'tForth': "Agente d'accueil | UEFA",
            'tFifth': "Master Tourisme Langues et Patrimoine | Aix-Marseille Université",
            'tSixth': "Assistante logistique | Benetton",
            'tSeventh': "Bibliothécaire | Aix-Marseille Université",
            'tEighth': "Assistante de français | Ecole et Collège de Amarante",
            'tNinth':"Assistante de Direction | Schindler Ireland",
            'tTenth':"Programme Erasmus | Universidade Católica Portuguesa ",
            'tEleventh': "Langues Etrangères Appliquées spécialité affaires et commerce | Aix-Marseille Université",
            'aa':"Sensibilisation au numérique",
            'ab':"Présentation des langages de programmation HTML/CSS",
            'ac':"Apprentissage de la conception de pages web",
            'ba':"Apprentissage des langages de programmation et des librairies",
            'bb':"Gestion de projets individuels et collectifs",
            'bc':"Utilisation du logiciel Linux",
            'ca':"Présentation de la surface de vente",
            'cb':"Accueil de la clientèle",
            'cc':"Gestion du stand de vente de la Foire de Marseille 2015 et du marché du Merlan",
            'da':"Accueil des spectateurs",
            'db':"Vérification des billets",
            'dc':"Orientation des supporters",
            'ea':"Conduite de projets",
            'eb':"Economie du tourisme",
            'ec':"Histoire de l'art",
            'fa':"Contrôle qualité",
            'fb':"Gestion des commandes",
            'fc':"Gestion des litiges",
            'fd':"Suivi logistique: mode de conditionnement",
            'ga':"Accueil du public",
            'gb':"Création et gestion d'une base de données",
            'gc':"Conseil des documents (livres et revues) auprès des étudiants",
            'gd':"Aide pédagogique aux étudiants: exposés, dissertation, thèses...",
            'ha':"Création, gestion et organisation des activités ludiques et pédagogiques",
            'hb':"Travail d'équipe avec les enseignants",
            'hc':"Promotion de la langue française",
            'ia':"Réception des appels téléphoniques",
            'ib':"Envoi des factures et retards de paiement",
            'ic':"Organisations des déplacements professionnels",
            'id':"Rédaction de notes de synthèses en français et en anglais",
            'ie':"Prospection d'entreprises",
            'ja':"Communication en entreprise",
            'jb':"Gestion des organisations",
            'jc':"Infographie - webdesign",
            'ka':"Economie",
            'kb':"Gestion et comptabilité",
            'kc':"Droit",
            'kd':"Marketing",
            'ke':"Developpement stratégique à l'international",
           'legal':"Mentions légales"
        },
        'en': {
            'home': "Home",
            'cv': "Resume",
            'pj': "Works",
            't': "Timeline",
            'tFirst': "Mediator numérique | Echanges Phocéens",
            'tSecond': "Web developper | Simplonmars Training",
            'tThird': "Volunteer Sales | Artisans du Monde",
            'tForth': "Volunteer Spectator Services | UEFA",
            'tFifth': "Master Degree in Tourism Languages and Patrimony | Aix-Marseille Université (AMU)",
            'tSixth': "Logistic assistant | Benetton",
            'tSeventh': "Librarian | AMU",
            'tEighth': "French assistant | Amarante school",
            'tNinth':"Executive assitant | Schindler Ireland",
            'tTenth':"Erasmus Exchange | Universidade Católica Portuguesa ",
            'tEleventh': 'Applied Foreign Languages: Business and Trading | AMU',
            'tn':"Foussana | Tunisia",
            'ie':"Dublin | Ireland",
            'pt':"Lisbon | Portugal",
            'aa':"Promote programming jobs",
            'ab':"Introduction to the programming languages HTML/CSS",
            'ac':"Teach how to conceive a webpage",
            'ba':"Learn programming languages and frameworks",
            'bb':"Manage individual and team projects",
            'bc':"Use of Linux software",
            'ca':"Facing",
            //translate
            'cb':"Accueil de la clientèle",
            'cc':"Gestion du stand de vente de la Foire de Marseille 2015 et du marché du Merlan",
            'da':"Accueil des spectateurs",
            'db':"Vérification des billets",
            'dc':"Orientation des supporters",
            'ea':"Conduite de projets",
            'eb':"Economie du tourisme",
            'ec':"Histoire de l'art",
            'fa':"Contrôle qualité",
            'fb':"Gestion des commandes",
            'fc':"Gestion des litiges",
            'fd':"Suivi logistique: mode de conditionnement",
            'ga':"Accueil du public",
            'gb':"Création et gestion d'une base de données",
            'gc':"Conseil des documents (livres et revues) auprès des étudiants",
            'gd':"Aide pédagogique aux étudiants: exposés, dissertation, thèses...",
            'ha':"Création, gestion et organisation des activités ludiques et pédagogiques",
            'hb':"Travail d'équipe avec les enseignants",
            'hc':"Promotion de la langue française",
            'ia':"Réception des appels téléphoniques",
            'ib':"Envoi des factures et retards de paiement",
            'ic':"Organisations des déplacements professionnels",
            'id':"Rédaction de notes de synthèses en français et en anglais",
            'ie':"Prospection d'entreprises",
            'ja':"Communication en entreprise",
            'jb':"Gestion des organisations",
            'jc':"Infographie - webdesign",
            'ka':"Economie",
            'kb':"Gestion et comptabilité",
            'kc':"Droit",
            'kd':"Marketing",
            'ke':"Developpement stratégique à l'international",
            'contact': "Contact",
            'legal': "Mentions"
        },
        'pt': {
            'home': "Início",
            'cv': "Currículo",
            'pj': "Portfolio",
            't': "Histórico",
            'tFirst': "Mediator numérique | Echanges Phocéens",
            'tSecond': "Web developper | Simplonmars Training",
            'tThird': "Vendora | Artisans du Monde",
            'tForth': "Volunteer Spectator Services | UEFA",
            'tFifth': "Mestrado Turismo Línguas e Património | Aix-Marseille Université (AMU)",
            'tSixth': "Logistic assistant | Benetton",
            'tSeventh': "Librarian | AMU",
            'tEighth': "French assistant | Amarante school",
            'tNinth':"Executive assitant | Schindler Ireland",
            'tTenth':"Mobilidade Livre Erasmus  | Universidade Católica Portuguesa ",
            'tEleventh': 'Línguas Estrangeiras Aplicados: Comércio e Negócios | AMU',
            'tn':"Foussana | Tunísia",
            'ie':"Dublin | Irlândia",
            'pt':"Lisboa | Portugal",
            //translate
            'aa':"Sensibilisation au numérique",
            'ab':"Présentation des langages de programmation HTML/CSS",
            'ac':"Apprentissage de la conception de pages web",
            'ba':"Apprentissage des langages de programmation et des librairies",
            'bb':"Gestion de projets individuels et collectifs",
            'bc':"Utilisation du logiciel Linux",
            'ca':"Présentation de la surface de vente",
            'cb':"Accueil de la clientèle",
            'cc':"Gestion du stand de vente de la Foire de Marseille 2015 et du marché du Merlan",
            'da':"Accueil des spectateurs",
            'db':"Vérification des billets",
            'dc':"Orientation des supporters",
            'ea':"Conduite de projets",
            'eb':"Economie du tourisme",
            'ec':"Histoire de l'art",
            'fa':"Contrôle qualité",
            'fb':"Gestion des commandes",
            'fc':"Gestion des litiges",
            'fd':"Suivi logistique: mode de conditionnement",
            'ga':"Accueil du public",
            'gb':"Création et gestion d'une base de données",
            'gc':"Conseil des documents (livres et revues) auprès des étudiants",
            'gd':"Aide pédagogique aux étudiants: exposés, dissertation, thèses...",
            'ha':"Création, gestion et organisation des activités ludiques et pédagogiques",
            'hb':"Travail d'équipe avec les enseignants",
            'hc':"Promotion de la langue française",
            'ia':"Réception des appels téléphoniques",
            'ib':"Envoi des factures et retards de paiement",
            'ic':"Organisations des déplacements professionnels",
            'id':"Rédaction de notes de synthèses en français et en anglais",
            'ie':"Prospection d'entreprises",
            'ja':"Communication en entreprise",
            'jb':"Gestion des organisations",
            'jc':"Infographie - webdesign",
            'ka':"Economie",
            'kb':"Gestion et comptabilité",
            'kc':"Droit",
            'kd':"Marketing",
            'ke':"Developpement stratégique à l'international",
            'contact': "Contato",
            'legal': "Menções legais"
        }
    };
    /**************loop lang elements to each item when element translate class is clicked***************/
    $(function() {
        /*****create an event onclick******************/
        $('.translate').click(function() {
            /**********create a var*************/
            var languages = $(this).attr('id');
            /**********target the class lang for the change*************/
            $('.lang').each(function(index, element) {
                $(this).text(translationArr[languages][$(this).attr('key')]);

            });
        });
    });
});
